namespace Chevito.FirstStepsInDdd
{
    public enum CriminalOffence
    {
        DANGEROUS_DRIVING,
        ENDANGERING_AN_AIRCRAFT,
        FALSE_ACCOUNTING,
        IMPERSONATING_CUSTOMS_OFFICER,
        KEEPING_A_DISORDERLY_HOUSE,
        CORRUPTION_IN_PUBLIC_OFFICE,
        CUTTING_AWAY_BUOYS_ETC,
        FALSE_EVIDENCE_BEFORE_EUROPEAN_COURT,
        FIRING_ON_REVENUE_VESSEL,
        FRAUDULENT_EVASION_OF_AGRICULTURAL_LEVY,
        OBSTRUCTING_ENGINE_OR_CARRIAGE_ON_RAILWAY
    }
}